#ifndef MH_TEXTURE_FORMATS_INCLUDED
#define MH_TEXTURE_FORMATS_INCLUDED

#include "Mahakam/Core/Enum.h"

namespace Mahakam
{
	MH_BEGIN_ENUM(TextureFormat)
	{
		MH_DECL_ENUM_ELEMENT(R8),
		MH_DECL_ENUM_ELEMENT(RG8),
		MH_DECL_ENUM_ELEMENT(RGB8),
		MH_DECL_ENUM_ELEMENT(RGBA8),
		MH_DECL_ENUM_ELEMENT(R16F),
		MH_DECL_ENUM_ELEMENT(RG16F),
		MH_DECL_ENUM_ELEMENT(RGB16F),
		MH_DECL_ENUM_ELEMENT(RGBA16F),
		MH_DECL_ENUM_ELEMENT(R32F),
		MH_DECL_ENUM_ELEMENT(RG32F),
		MH_DECL_ENUM_ELEMENT(RGB32F),
		MH_DECL_ENUM_ELEMENT(RGBA32F),
		MH_DECL_ENUM_ELEMENT(RG11B10F),
		MH_DECL_ENUM_ELEMENT(RGB10A2),
		MH_DECL_ENUM_ELEMENT(SRGB8),
		MH_DECL_ENUM_ELEMENT(SRGBA8),
		MH_DECL_ENUM_ELEMENT(R_BC4),
		MH_DECL_ENUM_ELEMENT(RG_BC5),
		MH_DECL_ENUM_ELEMENT(RGBA_BC7),
		MH_DECL_ENUM_ELEMENT(RGB_DXT1),
		MH_DECL_ENUM_ELEMENT(RGBA_DXT5),
		MH_DECL_ENUM_ELEMENT(SRGB_DXT1),
		MH_DECL_ENUM_ELEMENT(SRGB_DXT5),
		MH_DECL_ENUM_ELEMENT(Depth16),
		MH_DECL_ENUM_ELEMENT(Depth24),
		MH_DECL_ENUM_ELEMENT(Depth24Stencil8),
		MH_DECL_ENUM_ELEMENT(Count)
	}
	MH_END_ENUM(TextureFormat);

	MH_BEGIN_ENUM(TextureFilter)
	{
		MH_DECL_ENUM_ELEMENT(Point),
		MH_DECL_ENUM_ELEMENT(Bilinear),
		MH_DECL_ENUM_ELEMENT(Trilinear),
		MH_DECL_ENUM_ELEMENT(Count)
	}
	MH_END_ENUM(TextureFilter);

	MH_BEGIN_ENUM(TextureWrapMode)
	{
		MH_DECL_ENUM_ELEMENT(Repeat),
		MH_DECL_ENUM_ELEMENT(Clamp),
		MH_DECL_ENUM_ELEMENT(ClampBorder),
		MH_DECL_ENUM_ELEMENT(Count)
	}
	MH_END_ENUM(TextureWrapMode);

	MH_BEGIN_ENUM(TextureCubePrefilter)
	{
		MH_DECL_ENUM_ELEMENT(None),
		MH_DECL_ENUM_ELEMENT(Convolute),
		MH_DECL_ENUM_ELEMENT(Prefilter),
		MH_DECL_ENUM_ELEMENT(Count)
	}
	MH_END_ENUM(TextureCubePrefilter);
}

#endif