name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup premake
      uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"
    - name: Run premake
      run: premake5 gmake2
    - name: Install X11
      run: sudo apt-get install -y libx11-dev mesa-common-dev libglu1-mesa-dev libxrandr-dev libxi-dev libxcursor-dev 
    - name: Compile Erebor
      run: make -j 4 Erebor
